services:
    appdb:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-appdb}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-010203}
            POSTGRES_USER: ${POSTGRES_USER:-mobapp}
        networks:
            - mynetwork
        ports:
            - "5434:5432"
networks:
    mynetwork:
        driver: bridge